# Generated by Django 5.0.9 on 2024-12-03 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('IT & Business Support', 'IT & Business Support'), ('Finance', 'Finance'), ('Quality Assurance', 'Quality Assurance')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=100)),
                ('purchase_type', models.CharField(choices=[('Raw Material', 'Raw Material'), ('Spareparts', 'Spareparts'), ('Consumables', 'Consumables'), ('Indirect Goods', 'Indirect Goods'), ('Services', 'Services'), ('CAPEX/ Small Projects', 'CAPEX/ Small Projects')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=100)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='PR_api.purchaserequest')),
            ],
        ),
    ]
