# Generated by Django 5.0.9 on 2024-12-08 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_api', '0002_purchaserequest_purchaserequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(choices=[('IT & Business Support', 'IT & Business Support'), ('Finance', 'Finance'), ('Quality Assurance', 'Quality Assurance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_type',
            field=models.CharField(choices=[('Raw Material', 'Raw Material'), ('Spare parts', 'Spare parts'), ('Consumables', 'Consumables'), ('Indirect Goods', 'Indirect Goods'), ('Services', 'Services'), ('CAPEX/ Small Projects', 'CAPEX/ Small Projects')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='item_code',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='item_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='item_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='unit_of_measurement',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='purchaserequest',
            table='purchase_request',
        ),
        migrations.AlterModelTable(
            name='purchaserequestitem',
            table='purchase_request_item',
        ),
    ]
